[package]
name = "sptmm_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
sptmm_lib = {path = "../sptmm_lib"}
iced = {version = "0.12.1", features = ["default"]}
serde_json = "1.0.120"
serde = "1.0.203"
tokio = "1.38.0"